### ISSUE TITLE
Fix required in CMakeLists.txt

### ISSUE THREAD

**Issue by tusharathawale** [uo-cdux/vtk-m-tutorial#11]
Hello,

I ran into couple of issues when compiling tutorial examples using the CMakeLists.txt. I was getting linking errors and data access errors when I generated a makefile using CMakeLists.txt in the repository. 

I fixed the linking error by adding vtkm_rendering to target_link_libraries. Also I fixed data copy error in the last line of the CMakeLists.txt. With these two fixes, I was able to fix compilation issue. Note that I compiled tutorial examples on my Macbook Pro.

I have attached the new CMakeLists.txt.
[CMakeLists.txt](https://github.com/uo-cdux/vtk-m-tutorial/files/7549667/CMakeLists.txt)

Thanks,
Tushar

**Comment by vicentebolea** [comment]
@tusharathawale I appreciate this report.

Could you possibly open a Pull request with the changes that you had to make. Note that this tutorial has not been updated for the past two releases

**Comment by tusharathawale** [comment]
Hi,

I have created a Pull request. Can you please take a look?

Thanks,
Tushar

**Comment by vicentebolea** [comment]
@tusharathawale you can close this

**Comment by tusharathawale** [comment]
@vicentebolea: Closed it, thanks.
